### ISSUE TITLE
0.17.2 does not compile with gpsd v3.1 (redmine import 3304, Yclept Nemo, created 09/27/2011) 

### ISSUE THREAD

**Issue by Krakonos** [Krakonos/merkaartor-oldbugs#17]
GPS/qgpsdevice.cpp: In member function ‘bool QGPSDevice::parseGSV(const char_)’:
GPS/qgpsdevice.cpp:577:9: warning: variable ‘totalSentences’ set but not used [-Wunused-but-set-variable]
GPS/qgpsdevice.cpp:578:9: warning: variable ‘currentSentence’ set but not used [-Wunused-but-set-variable]
GPS/qgpsdevice.cpp:579:9: warning: variable ‘totalSatellites’ set but not used [-Wunused-but-set-variable]
GPS/qgpsdevice.cpp: In member function ‘virtual void QGPSDDevice::run()’:
GPS/qgpsdevice.cpp:962:24: error: no matching function for call to ‘gpsmm::gpsmm()’
GPS/qgpsdevice.cpp:962:24: note: candidates are:
/usr/include/libgpsmm.h:21:3: note: gpsmm::gpsmm(const char_, const char_)
/usr/include/libgpsmm.h:21:3: note:   candidate expects 2 arguments, 0 provided
/usr/include/libgpsmm.h:15:7: note: gpsmm::gpsmm(const gpsmm&)
/usr/include/libgpsmm.h:15:7: note:   candidate expects 1 argument, 0 provided
GPS/qgpsdevice.cpp:964:23: error: ‘class gpsmm’ has no member named ‘open’
GPS/qgpsdevice.cpp:981:29: error: no matching function for call to ‘gpsmm::waiting()’
GPS/qgpsdevice.cpp:981:29: note: candidate is:
/usr/include/libgpsmm.h:35:8: note: bool gpsmm::waiting(int)
/usr/include/libgpsmm.h:35:8: note:   candidate expects 1 argument, 0 provided
GPS/qgpsdevice.cpp: In member function ‘virtual void QGPSDDevice::onDataAvailable()’:
GPS/qgpsdevice.cpp:997:29: error: no matching function for call to ‘gpsmm::waiting()’
GPS/qgpsdevice.cpp:997:29: note: candidate is:
/usr/include/libgpsmm.h:35:8: note: bool gpsmm::waiting(int)
/usr/include/libgpsmm.h:35:8: note:   candidate expects 1 argument, 0 provided
make[1]: *_\* [qgpsdevice.o] Error 1
